### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by alex-wilmer** [trayio/babel-plugin-webpack-alias#1]
Not sure what I'm missing to get this to work.

Error:

```
app/ui/src/utils/api.js: Path must be a string. Received undefined
```

api.js

```
import { domain } from 'config'
```

.babelrc

```
{
  "env": {
   "development": {
     "plugins": [
        [ "babel-plugin-webpack-alias", { "config": "./webpack.config.js" } ]
      ]
    }
  }
}
```

webpack.config.js

```
var path = require('path')
var webpack = require('webpack')

module.exports = {
  devtool: 'eval',
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    './src/index',
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/',
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: [ 'react-hot', 'babel' ],
        include: path.join(__dirname, 'src'),
      },
      { test: /\.styl$/, loader: 'style-loader!css-loader!stylus-loader' },
    ],
  },
  resolve: {
    root: path.resolve(__dirname),
     alias: {
       config: path.join(__dirname, 'config', process.env.NODE_ENV),
     },
     extensions: ['', '.js', '.styl'],
  },
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    bufferutil: 'empty',
  },
}
```

**Comment by grrowl** [comment]
I'm getting the same, oddly enough babel-plugin-webpack-alias seems to be doing the right thing: I thought line 26 was suspicious (`const conf = require((0, _path.resolve)(process.cwd(), configPath));`) but it's correctly resolving to the full filename of my webpack.config.js. The errors come further down, through babel-register, and even there the `filename` is set correctly for this and previous invocations (such as `test.js`). :confused:

**Comment by grrowl** [comment]
Your problem is here:
```
  resolve: {
    root: path.resolve(__dirname),
     alias: {
       config: path.join(__dirname, 'config', process.env.NODE_ENV),
     },
     extensions: ['', '.js', '.styl'],
  },
```

I'm guessing NODE_ENV isn't defined, so `path` is receiving `path.join(__dirname, 'config', undefined) and failing. The stacktrace lies a little. If this isn't the case, check other use of `path` within your app.

**Comment by grrowl** [comment]
Also you will get this error if any of your values are undefined, such as config:

```
    alias: {
      shared: path.resolve('shared/app'),
      traits: path.resolve('shared/app/styles/traits'),
      someValue: undefined // for whatever reason
    },
```

Error stack:
```
TypeError: /Users/tom/Documents/activepipe/activepipe.com/tests.js: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at posix.isAbsolute (path.js:470:3)
    at PluginPass.CallExpression (/Users/tom/Documents/activepipe/activepipe.com/node_modules/babel-plugin-webpack-alias/build/index.js:55:51) # <<<
    at newFn (/Users/tom/Documents/activepipe/activepipe.com/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/tom/Documents/activepipe/activepipe.com/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/tom/Documents/activepipe/activepipe.com/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/tom/Documents/activepipe/activepipe.com/node_modules/babel-traverse/lib/path/context.js:93:12)
```

**Comment by alex-wilmer** [comment]
@grrowl  Thanks for taking a look. I'm going to try again later but I was able to solve my general problem by updating my test script ala http://stackoverflow.com/questions/33793504/using-webpack-aliases-in-mocha-tests

```
"test": "find ./src -name '*.test.js' | NODE_PATH=./src xargs mocha -r babel-core/register -r mock-local-storage"
```

**Comment by adriantoine** [comment]
Closing the issue as this doesn't seem to be an issue related to this plugin.
