### ISSUE TITLE
Not currently working at all with ava

### ISSUE THREAD

**Issue by joeyfigaro** [trayio/babel-plugin-webpack-alias#42]
**Dependencies**
```json
"ava": "^0.16.0",
"babel-core": "^6.18.2",
"babel-plugin-webpack-alias": "^2.1.2",
"webpack": "^1.13.3"
```

**Babel config**
```json
{
	"only": [
		"*.js",
		"*.test.js",
		"*.babel.js"
	],
	"ignore": [
		"./node_modules",
		"./node_modules/**/node_modules"
	],
	"presets": ["react", "es2015", "es2016", "stage-0"],
	"plugins": [
		"transform-object-rest-spread",
		["webpack-alias", {
			"config": "${PWD}/config/webpack/development.js"
		}]
	],
	"env": {
		"development": {
			"plugins": [
				"transform-class-properties",
				"react-hot-loader/babel"
			]
		},
		"test": {
			"plugins": [

			]
		}
	}
}
```

**Webpack config**
```js
/* eslint-disable */
var webpack = require('webpack');
var path = require('path');
var BundleTracker = require('webpack-bundle-tracker');
var ROOT_PATH = path.resolve(__dirname, '..', '..');
var ExtendedDefinePlugin = require('extended-define-webpack-plugin');
var apiSettings = require('./common').API_CONFIG['development'];
var appSettings = require('./common').APP_CONFIG['development'];

module.exports = {
	debug: true,
	devtool: 'eval-source-map',
	entry: [
		'webpack-hot-middleware/client',
		'webpack/hot/only-dev-server',
		'babel-polyfill',
		path.resolve(ROOT_PATH, 'src', 'client', 'index')
	],
	output: {
		path: path.resolve(__dirname, '/'),
		publicPath: 'http://localhost:8080/static/',
		filename: 'client.js'
	},
	module: {
		loaders: [
			{
				test: /\.css$/,
				loader: 'style-loader!css-loader'
			},
			{
				test: /\.js$/,
				exclude: [/node_modules/],
				loaders: ['babel']
			}
		]
	},
	resolve: {
		alias: {
			'seeds': path.resolve(ROOT_PATH, 'seeds'),
			'client/containers': path.join(ROOT_PATH, 'src', 'client', 'containers'),
			'client/actions': path.join(ROOT_PATH, 'src', 'client', 'actions'),
			'client/middleware':  path.join(ROOT_PATH, 'src', 'client', 'middleware'),
			'client/routes':  path.join(ROOT_PATH, 'src', 'client', 'routes'),
			'client/store': path.join(ROOT_PATH, 'src', 'client', 'store'),
			'client/sagas': path.join(ROOT_PATH, 'src', 'client', 'sagas'),
			'client/utils':  path.join(ROOT_PATH, 'src', 'client', 'utils'),
			'client/reducers': path.join(ROOT_PATH, 'src', 'client', 'reducers'),
			'server/utils':  path.join(ROOT_PATH, 'src', 'server', 'utils'),
		},
		extensions: ['.js', '']
	},
	plugins: [
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin(),
		new ExtendedDefinePlugin({
			'process.env': {
				'NODE_ENV': 'development'
			},
			API_SETTINGS: apiSettings,
			APP_SETTINGS: appSettings,
			__DEVELOPMENT__: true,
			__PRODUCTION__: false,
			__DEVTOOLS__: true
		}),
		new BundleTracker({
			path: ROOT_PATH,
			filename: './webpack-stats.json'
		})
	],
};
```

**AVA config**
```json
"ava": {
    "files": [
      "__tests__/**/*.js"
    ],
    "concurrency": 5,
    "failFast": true,
    "tap": true,
    "powerAssert": true,
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  }
```

**Project Structure**
```
- __tests__
    - reducers
        - app.js
    - selectors
        - transactions.js
- config
- seeds
- src
    - client
        - actions
            App.js
            index.js
            Segment.js
            Session.js
        ...
        ...
        ...
```

**Test Script**
`"PWD=$(pwd) NODE_ENV=test BABEL_DISABLE_CACHE=1 ava --serial --verbose --tap | tap-nyan"`

**Error**
```
Error: Cannot find module 'client/actions/App'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joeyfigaro/work/projects/app/__tests__/reducers/app.js:5:1)
    at Module._compile (module.js:541:32)
    at extensions.(anonymous function) (/Users/joeyfigaro/work/projects/app/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/joeyfigaro/work/projects/app/node_modules/ava/lib/test-worker.js:92:3)
```

It doesn't look like it's even using the webpack config - if I add `console.log()` to my config, nothing shows up when I run my test script. I've attempted to move the webpack config to root and have tried renaming it to the default name the plugin looks for to no avail.

Have I missed something obvious here?

**Comment by joeyfigaro** [comment]
Looks like Ava recently released `0.17.0` and it seems to have fixed the issue 😄 : https://github.com/avajs/ava/releases/tag/v0.17.0
